# general settings
name: SAIGFormer_SID
model_type: ImageCleanModel
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_SIDImage
    # interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_gt: /home/fds-admin/user_files/lihanting/SID/long_sid2
    dataroot_lq: /home/fds-admin/user_files/lihanting/SID/short_sid2
    train_size: 256
    cache_keys: ~
    cache_data: true
    padding: new_info

    filename_tmpl: '{}'
    io_backend:
      type: disk

    N_frames: 5     # how many frames as a input.
    # data argument
    use_flip: true
    use_rot: true
    color: RGB
    
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4

    mini_batch_sizes: [4]   
    iters: [300000]
    gt_size: 256
    gt_sizes: [256]
    geometric_augs: true

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_SIDImage
    dataroot_gt: /home/fds-admin/user_files/lihanting/SID/long_sid2
    dataroot_lq: /home/fds-admin/user_files/lihanting/SID/short_sid2
    cache_data: true
    N_frames: 5
    padding: new_info
    train_size: [960, 512]
    io_backend:
      type: disk
    val_batch_size: 4
    val_num_worker: 8

# network structures
network_g:
  type: SAIGFormer
  embed_dim: 32

  train_patch: 256
  eps: !!float 1e-1



# path
path:
  root: /home/fds-admin/user_files/lihanting/model_output/SID
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 300000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  

  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    - type: L1Loss
      loss_weight: 1
      reduction: mean
    - type: SSIMLoss

# validation settings
val:
  window_size: 4
  val_freq: !!float 1e3
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  logger_path: /home/fds-admin/user_files/lihanting/model_output/SID
  wandb:
    project: low_light
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
