# general settings
name: SAIGFormer_lolv2_real
model_type: ImageCleanModel
use_amp: False
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: /home/fds-admin/user_files/lihanting/LOLv2/Real_captured/Train/Normal
    dataroot_lq: /home/fds-admin/user_files/lihanting/LOLv2/Real_captured/Train/Low
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    mini_batch_sizes: [8]   
    iters: [300000]
    gt_size: 128   
    gt_sizes: [128]

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: /home/fds-admin/user_files/lihanting/LOLv2/Real_captured/Test/Normal
    dataroot_lq: /home/fds-admin/user_files/lihanting/LOLv2/Real_captured/Test/Low
    io_backend:
      type: disk
    val_batch_size: 4
    val_num_worker: 8

# network structures
network_g:
  type: SAIGFormer
  embed_dim: 32

  train_patch: 128
  eps: !!float 1e-1


# path
path:
  root: /home/fds-admin/user_files/lihanting/model_output/LOLv2_real
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 300000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]       
    restart_weights: [1,1]
    eta_mins: [0.0001,0.000001]   
  

  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 4e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    - type: L1Loss
      loss_weight: 1
      reduction: mean
    - type: SSIMLoss


# validation settings
val:
  window_size: 4
  val_freq: !!float 0.5e2
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  logger_path: /home/fds-admin/user_files/lihanting/model_output/LOLv2_real
  wandb:
    project: low_light
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
